services:
  proxy:
    image: nginx:1.25-alpine
    container_name: proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-blue
      - app-green

  app-blue:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app-blue
    ports:
      - "8081:8080"
    expose:
      - "8080"

  app-green:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app-green
    ports:
      - "8082:8080"
    expose:
      - "8080"