name: Deployment Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build_and_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build (skip tests)
        run: mvn -B -U -DskipTests package

      - name: Unit tests
        run: mvn -B -DskipITs test

      - name: Integration tests
        run: mvn -B verify

      - name: Acceptance tests
        run: mvn -B -P acceptance verify

      - name: Archive artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-artifacts
          path: |
            target/*.jar
            target/surefire-reports/**
            target/failsafe-reports/**

  deploy_to_test:
    runs-on: ubuntu-latest
    needs: build_and_tests
    env:
      SLOT_ACTIVE_FILE: .deployment/active-slot.txt
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-artifacts
          path: dist

      - name: Determine idle slot
        id: slots
        shell: bash
        run: |
          ACTIVE="blue"
          if [ -f "${SLOT_ACTIVE_FILE}" ]; then
            ACTIVE=$(cat "${SLOT_ACTIVE_FILE}")
          fi
          if [ "$ACTIVE" = "blue" ]; then
            echo "idle=green" >> "$GITHUB_OUTPUT"
          else
            echo "idle=blue" >> "$GITHUB_OUTPUT"
          fi

      - name: Deploy to idle slot
        shell: bash
        run: |
          IDLE="${{ steps.slots.outputs.idle }}"
          mkdir -p ".deployment/${IDLE}"
          cp dist/*.jar ".deployment/${IDLE}/app.jar"
          echo "Deployed to slot ${IDLE}"

      - name: Post-deploy smoke check
        shell: bash
        run: |
          IDLE="${{ steps.slots.outputs.idle }}"
          test -f ".deployment/${IDLE}/app.jar"

      - name: Switch traffic (Blue-Green)
        shell: bash
        run: |
          echo "${{ steps.slots.outputs.idle }}" > "${SLOT_ACTIVE_FILE}"
          echo "Active slot is now $(cat ${SLOT_ACTIVE_FILE})"

      - name: Upload deployment state
        uses: actions/upload-artifact@v4
        with:
          name: deployment-state
          path: .deployment

  rollback:
    runs-on: ubuntu-latest
    needs: deploy_to_test
    if: failure()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Attempt rollback to previous slot
        shell: bash
        run: |
          if [ -f ".deployment/active-slot.txt" ]; then
            CUR=$(cat .deployment/active-slot.txt)
            if [ "$CUR" = "blue" ]; then PREV="green"; else PREV="blue"; fi
            echo "$PREV" > .deployment/active-slot.txt
            echo "Rolled back to $PREV"
          else
            echo "No active slot info found"; exit 1
          fi